/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Cs55Plus: typeof import('./src/components/Cs55Plus.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
  }
}
